SELECT i.FOOD_TYPE, i.REST_ID, i.REST_NAME, mf.FAVORITES
FROM REST_INFO i
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS mf ON i.FOOD_TYPE = mf.FOOD_TYPE AND i.FAVORITES = mf.FAVORITES
ORDER BY i.FOOD_TYPE DESC;
