SELECT f.CATEGORY, max_prices.MAX_PRICE, f.PRODUCT_NAME
FROM FOOD_PRODUCT f
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS max_prices ON f.CATEGORY = max_prices.CATEGORY AND f.PRICE = max_prices.MAX_PRICE
ORDER BY max_prices.MAX_PRICE DESC;